CREATE CONSTRAINT source_id IF NOT EXISTS FOR (n:Source) REQUIRE n.source_id IS UNIQUE;
CREATE CONSTRAINT document_id IF NOT EXISTS FOR (n:Document) REQUIRE n.document_id IS UNIQUE;
CREATE CONSTRAINT document_version_id IF NOT EXISTS FOR (n:DocumentVersion) REQUIRE n.document_version_id IS UNIQUE;
CREATE CONSTRAINT chunk_id IF NOT EXISTS FOR (n:Chunk) REQUIRE n.chunk_id IS UNIQUE;
CREATE CONSTRAINT contributor_id IF NOT EXISTS FOR (n:Contributor) REQUIRE n.contributor_id IS UNIQUE;
CREATE CONSTRAINT organization_id IF NOT EXISTS FOR (n:Organization) REQUIRE n.organization_id IS UNIQUE;
CREATE CONSTRAINT country_id IF NOT EXISTS FOR (n:Country) REQUIRE n.country_id IS UNIQUE;
CREATE CONSTRAINT domain_id IF NOT EXISTS FOR (n:Domain) REQUIRE n.domain_id IS UNIQUE;
CREATE CONSTRAINT assertion_id IF NOT EXISTS FOR (n:Assertion) REQUIRE n.assertion_id IS UNIQUE;
CREATE CONSTRAINT run_id IF NOT EXISTS FOR (n:ProcessingRun) REQUIRE n.run_id IS UNIQUE;
CREATE CONSTRAINT claim_group_id IF NOT EXISTS FOR (n:ClaimGroup) REQUIRE n.claim_group_id IS UNIQUE;
CREATE CONSTRAINT evidence_family_id IF NOT EXISTS FOR (n:EvidenceFamily) REQUIRE n.family_id IS UNIQUE;
CREATE CONSTRAINT technology_concept_id IF NOT EXISTS FOR (n:Technology) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT method_concept_id IF NOT EXISTS FOR (n:Method) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT task_concept_id IF NOT EXISTS FOR (n:Task) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT problem_concept_id IF NOT EXISTS FOR (n:Problem) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT application_concept_id IF NOT EXISTS FOR (n:ApplicationContext) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT metric_concept_id IF NOT EXISTS FOR (n:Metric) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT material_concept_id IF NOT EXISTS FOR (n:Material) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT domain_concept_id IF NOT EXISTS FOR (n:Domain) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT market_segment_concept_id IF NOT EXISTS FOR (n:MarketSegment) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT organization_concept_id IF NOT EXISTS FOR (n:Organization) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT company_concept_id IF NOT EXISTS FOR (n:Company) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT university_concept_id IF NOT EXISTS FOR (n:University) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT country_concept_id IF NOT EXISTS FOR (n:Country) REQUIRE n.concept_id IS UNIQUE;
CREATE CONSTRAINT candidate_concept_id IF NOT EXISTS FOR (n:ConceptCandidate) REQUIRE n.concept_id IS UNIQUE;
CREATE INDEX country_code IF NOT EXISTS FOR (n:Country) ON (n.code);
CREATE INDEX solves_version IF NOT EXISTS FOR ()-[r:SOLVES]-() ON (r.document_version_id);
CREATE INDEX developed_by_version IF NOT EXISTS FOR ()-[r:DEVELOPED_BY]-() ON (r.document_version_id);
CREATE INDEX used_by_version IF NOT EXISTS FOR ()-[r:USED_BY]-() ON (r.document_version_id);
CREATE INDEX funded_by_version IF NOT EXISTS FOR ()-[r:FUNDED_BY]-() ON (r.document_version_id);
CREATE INDEX developed_in_version IF NOT EXISTS FOR ()-[r:DEVELOPED_IN]-() ON (r.document_version_id);
CREATE INDEX located_in_version IF NOT EXISTS FOR ()-[r:LOCATED_IN]-() ON (r.document_version_id);
CREATE INDEX subtechnology_of_version IF NOT EXISTS FOR ()-[r:SUBTECHNOLOGY_OF]-() ON (r.document_version_id);
